name: Python Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pysrt requests pydub moviepy werkzeug

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvzf ngrok-v3-stable-linux-amd64.tgz
        sudo mv ngrok /usr/local/bin

    - name: Authenticate ngrok
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Flask server
      run: |
        nohup python lt-git.py &  # Start Flask server in the background
        sleep 10

    - name: Start ngrok
      run: |
        nohup ngrok http 5000 &  # Start ngrok in the background
        sleep 10

    - name: Get ngrok URL
      run: |
        curl --silent --show-error http://127.0.0.1:4040/api/tunnels > tunnels.json
        cat tunnels.json
      shell: bash

    - name: Keep the workflow running
      run: |
        echo "Keeping the workflow running for 6 hours..."
        sleep 21600
